config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get 'home/index'
  get 'home/about'
  get '/forbidden', to: 'home#forbidden'
  
  get    '/profile',       to: 'users#show'
  get    '/profile/edit',  to: 'users#edit'
  patch  '/profile/edit',  to: 'users#update'
  delete '/profile',       to: 'users#destroy'
  
  get    '/edit/password', to: 'users#edit_password'
  patch  '/edit/password', to: 'users#update_password'

  get    '/login',   to: 'session#new'
  post   '/login',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'

  root 'home#index'

  resources :users, only: [:new, :create]
  resources :articles
  resources :comments, only: [:update, :create, :destroy, :new, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :presence => true, :uniqueness => true, :length => {:in => 1..120}
  validates :content, :presence => true 
  
  belongs_to :user
  has_many :comments, :dependent => :delete_all
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :presence => true, :length => {:in => 1..500}
  
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, :presence => true, :uniqueness => true, :length => {:in => 3..20}
  	validates :email, :presence => true, :uniqueness => true
  	validates :password, :presence => true 
	has_many :comments,	:dependent => :delete_all
	has_many :articles,	:dependent => :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :require_login, except: [:index, :show]
  before_action :get_instance, except: [:index, :new, :create]
  before_action :check_rights, only: [:edit, :destroy, :update]

  def index
  	@articles = Article.all
  end

  def show
  	@comments = Comment.where(article_id: @article.id)
  end

  def new
  	@article = Article.new
  end

  def edit
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path
      flash[:success] = "Edit successfull"
    else
      render 'edit'
      flash[:danger] = "Edit failed"
    end
  end

  def create
  	@article = Article.new(article_params)
    @article.user_id = current_user.id
  	if @article.save
      redirect_to articles_path
  	  flash[:success] = "Article created successfully"
    else
      redirect_to new_article_path
      flash[:danger] = "Form is invalid"
  	end
  end

private

  def require_login
    if !current_user
      redirect_to login_path
    end
  end

  def get_instance
    @article = Article.find(params[:id])
  end

  def check_rights
    if @article.user_id != current_user.id && !current_user.is_staff
      redirect_to forbidden_path
    end
  end
  
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :require_login
  before_action :get_instance, :check_rights, only: [:edit, :destroy, :update]
  
  def new
  	@comment = Comment.new
  end

  def edit
  end

  def destroy
    @comment.destroy
    redirect_to article_path(@comment.article_id)
  end

  def update
    if @comment.update(comment_params)
      redirect_to article_path(@comment.article_id)
      flash[:success] = "Edit successfull"
    else
      render 'edit'
      flash[:danger] = "Edit failed"
    end
  end

  def create
    @comment = Comment.new(comment_params)
  	@comment.user_id = current_user.id

  	if @comment.save
      redirect_to article_path(@comment.article_id)
  	  flash[:success] = "Сomment created successfully"
    else
      redirect_to new_comment_path
      flash[:danger] = "Form is invalid"
  	end
  end

  private

    def require_login
      if !current_user
        redirect_to login_path
      end
    end

    def get_instance
      @comment = Comment.find(params[:id])
    end

    def check_rights
      if @comment.user_id != current_user.id && !current_user.is_staff
        redirect_to forbidden_path
      end
    end
      
    def comment_params
      params.require(:comment).permit(:content, :article_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def forbidden
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.password == params[:session][:password]
      log_in user
      flash[:success] = "Login successful"
      redirect_to home_index_path
    else
      flash[:danger] = "Wrong email/password!"
      render 'new'
    end
  end

  def destroy
  	log_out
  	redirect_to home_index_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, :get_instance, except: [:new, :create]

  def show
  end

  def new
  	@user = User.new
  end

  def edit
  end

  def destroy
    current_user.destroy
    log_out
    redirect_to home_index_path
  end

  def update
    if current_user.update(user_params)
      redirect_to profile_path
      flash[:success] = "Edit successfull"
    else
      render 'edit'
      flash[:danger] = "Edit failed"
    end
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
      log_in(@user)
      redirect_to profile_path
  	  flash[:success] = "User created successfully. Please, edit your profile"
    else
      redirect_to new_user_path
      flash[:danger] = "Form is invalid"
  	end
  end

  def edit_password 
  end

  def update_password
    if @user.password == params[:old_password] && @user.update(params.permit(:password))
      redirect_to profile_path
      flash[:success] = "Edit successfull"
    else
      render 'edit_password'
      flash[:danger] = "Incorrect password"
    end
  end
  
private

  def require_login
    if !current_user
      redirect_to login_path
    end
  end

  def get_instance
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :first_name, :last_name, :country, :about, :birthday, :is_staff)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    reset_session
  end

  def current_user
    if session[:user_id]
      return User.find_by(id: session[:user_id])
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<% provide(:title, "Edit article") %>

<div class="container">
  <div class="jumbotron">
	<%= form_with(model: @article, local: true) do |f| %>
	  <%= f.label :title %>
	  <%= f.text_field :title %><br><br>

	  <%= f.label :content %>
	  <%= f.text_area :content %><br><br>

	  <%= f.submit "Update", class: "btn btn-primary" %>
	<% end %>    
  </div>
</div>

app/views/articles/index.html.erb
<% provide(:title, "News") %>


<% @articles.each do |article| %>
	<div class="well">
		<h3><%= link_to article.title, article_path(article) %></h3>
		<h5><%= article.created_at %></h5>
		<h5><%= User.find(article.user_id).name %></h5>
	</div>
<% end %>

<% if current_user %>
	<div class="well">
		<%= link_to "To create new article press here..", new_article_path, {class: 'btn btn-info'} %>
	</div>
<% end %>

app/views/articles/new.html.erb
<% provide(:title, "Creating new article") %>

<div class="container">
  <div class="jumbotron">
	<%= form_for(@article) do |f| %>
	  <%= f.label :title %>
	  <%= f.text_field :title %><br><br>

	  <%= f.label :content %>
	  <%= f.text_area :content %><br><br>

	  <%= f.submit "Create", class: "btn btn-primary" %>
	<% end %>
  </div>
</div>

app/views/articles/show.html.erb
<% provide(:title, "Article") %>

<div class="container">
  <div class="jumbotron">
    <h3 class="test-info" align="center"><%= @article.title %></h3>
    <h5 class="test-info">Published: <%= @article.created_at %> by <%= User.find(@article.user_id).name %></h5>
    <%= @article.content %><br>
    <h5 align="right">
      <% if current_user %>
        <%= link_to new_comment_path(article_id: @article.id) do %>
		      <i class="glyphicon glyphicon-comment"></i> 
	      <% end %>
      <% end %>
        
      <% if current_user && (current_user.id == @article.user_id || current_user.is_staff) %>
        <%= link_to edit_article_path(@article) do %>
		      <i class="glyphicon glyphicon-edit"></i> 
	      <% end %>     
      
        <%= link_to article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } do %>
		      <i class="glyphicon glyphicon-remove"></i> 
	      <% end %>
      <% end %> 
    </h5>
  </div>
</div>
<div class="container">
  <h3 class="test-info" align="center">Comment section</h3>
  <% if current_user %>  
    <% if @comments.exists? == false %>
      <h4 align="center" class="test-info">There is no comments for this article yet...</h4>
    <% else %>
      <% @comments.each do |comment| %>
        <div class="jumbotron">
          <%= comment.content %>
          <h6 class="test-info" align="right">Published: <%= comment.created_at %> by <%= User.find(comment.user_id).name %></h6>
          <% if current_user && (current_user.id == comment.user_id || current_user.is_staff) %>
            <h5 align="right">
              <%= link_to edit_comment_path(comment) do %>
                <i class="glyphicon glyphicon-edit"></i> 
              <% end %>
        
              <%= link_to comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="glyphicon glyphicon-remove"></i> 
              <% end %>
            </h5>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <h4 align="center" class="test-info">This section is visible only for users</h4>
  <% end %>
</div>

app/views/comments/edit.html.erb
<% provide(:title, "Edit comment") %>

<div class="container">
  <div class="jumbotron">
	<%= form_with(model: @comment, local: true) do |f| %>
	  <%= f.label :content %>
  	  <%= f.text_area :content %><br><br>

	  <%= f.submit "Update", class: "btn btn-primary" %>
	<% end %>    
  </div>
</div>

app/views/comments/new.html.erb
<% provide(:title, "Creating new comment") %>

<div class="container">
  <div class="jumbotron">
	<%= form_for(@comment) do |f| %>
	  <%= f.label :content %>
	  <%= f.text_area :content %><br><br>
	  
	  <%= f.hidden_field :article_id, :value => params[:article_id] %>

	  <%= f.submit "Create", class: "btn btn-primary" %>
	<% end %>  
  </div>
</div>

app/views/home/about.html.erb
<% provide(:title, "About page") %>

<p>This is about page</p>

app/views/home/forbidden.html.erb
<% provide(:title, "Page forbidden") %>
<div class="container">
	<div class="jumbotron">
		<h2 align="center" style="bold">You have no rights to preform this action...</h2>
	</div>
</div>

app/views/home/index.html.erb
<% provide(:title, "Home page") %>
<p>This is home page</p>
<% if current_user %>
	<p>Welcome, <%= current_user.name %>!</p>
<% else %>
	<p>Sign In to gain access to more functionality</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all" %>
  	<%= stylesheet_link_tag    "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" %>
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" %>
    <%= javascript_include_tag "rails" %>
  </head>

  <body>
  	<nav class="navbar navbar-inverse">
  		<div class="container-fluid">
    		<div class="navbar-header">
      			<a class="navbar-brand" href="<% if current_user %> <%= profile_path %> <% else %>#<% end %>">Profile</a>
    		</div>
    		<ul class="nav navbar-nav">
      			<li <% if params[:controller]=="home" &&  params[:action]=="index" %>class="active"<% end %>>
      				<%= link_to "Home", home_index_path %>
      			</li>
      			<li <% if params[:controller]=="articles" %>class="active"<% end %>>
					<%= link_to "News", articles_path %>
      			</li>
      			<li <% if params[:controller]=="home" &&  params[:action]=="about"%>class="active"<% end %>>
      				<%= link_to "About", home_about_path %>
      			</li>
    		</ul>
    		<div class="nav navbar-nav navbar-right">
          <% if not current_user %>
      			<%= link_to "Log In", login_path, {class: 'btn btn-primary navbar-btn'} %>
          <% else %>
            <%= link_to "Log Out", logout_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
          <% end %>
      	</div>
  		</div>
	  </nav>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </body>
</html>

app/views/session/new.html.erb
<% provide(:title, "Log in") %>

<div class="container-fluid well span6" style="width:80%;">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(:session, url: login_path) do |f| %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <br><%= f.submit "Log in", class: "btn btn-primary" %>
      <% end %>

      <p><%= link_to "Create new user", new_user_path, {class: 'btn btn-info navbar-btn'} %></p>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user info") %>

<div class="container-fluid well span6" style="width:80%;">
	<div class="row-fluid">
        <div class="span8">
			<%= form_with(model: @user, url: profile_edit_path, local: true) do |f| %>
			  <%= f.label :name %>
			  <%= f.text_field :name %><br><br>

			  <%= f.label :email %>
			  <%= f.email_field :email %><br><br>

			  <%= f.label :first_name %>
			  <%= f.text_field :first_name %><br><br>

			  <%= f.label :last_name %>
			  <%= f.text_field :last_name %><br><br>

			  <%= f.label :birthday %>
			  <%= f.date_field :birthday %><br><br>

			  <%= f.label :country %>
			  <%= f.text_field :country %><br><br>

			  <%= f.label :about %>
			  <%= f.text_area :about %><br><br>

			  <%= f.submit "Update", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/edit_password.html.erb
<% provide(:title, "Change password") %>

<div class="container-fluid well span6" style="width:80%;">
	<div class="row-fluid">
        <div class="span8">
			<form action=<%= edit_password_path %> accept-charset="UTF-8" method="post">
			  <%= token_tag %>
			  <input type="hidden" name="_method" value="patch" />
			  <input type="hidden" name="id" value="<%= current_user.id %>" />
			  
			  <label for="password">New Password</label>
			  <input id="password" type="password" name="password" /><br><br>
			  
			  <label for="confirmation">Enter current password</label>
			  <input id="confirmation" type="password" name="old_password" /><br><br>

			  <input type="submit" name="commit" value="Update" class="btn btn-primary" data-disable-with="Update" />
			</form>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Creating new user") %>
<div class="container-fluid well span6" style="width:80%;">
	<div class="row-fluid">
        <div class="span8">
			<%= form_for(@user) do |f| %>
			  <%= f.label :name %>
			  <%= f.text_field :name %><br><br>

			  <%= f.label :email %>
			  <%= f.email_field :email %><br><br>

			  <%= f.label :password %>
			  <%= f.password_field :password %><br><br>

			  <%= f.submit "Create", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, "User Profile") %>

<div class="container-fluid well span6" style="width:80%;">
	<div class="row-fluid">
        <div class="span8">
            <h3><%= @user.name %></h3>
            <% if @user.first_name %> 
				<h6>First name: <%= @user.first_name %></h6>
			<% end %>
            <% if @user.last_name %> 
				<h6>Last name: <%= @user.last_name %></h6>
			<% end %>
            <h6>Email: <%= @user.email %></h6>
			<% if @user.country %> 
				<h6>Country: <%= @user.country %></h6>
			<% end %>
            <% if @user.birthday %> 
				<h6>Birthday: <%= @user.birthday %></h6>
			<% end %>
            <% if @user.about %> 
				<h6>About: <%= @user.about %></h6>
			<% end %>
			<h6>Registration date: <%= @user.created_at %></h6>
        </div>

        <div class="dropdown" align="right">
            <div class="btn-group">
                <a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
                    Action
                    <span class="glyphicon glyphicon-cog"></span>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                	<li>
                    	<%= link_to "Modify profile", profile_edit_path, {class: 'btn btn-success navbar-btn'} %>
                    </li>
                    
                    <li>
                    	<%= link_to "Change password", edit_password_path, {class: 'btn btn-success navbar-btn'} %>
                    </li>

                    <li>
                    	<%= link_to "Delete", profile_path, method: :delete, class: 'btn btn-danger navbar-btn', data: { confirm: 'Are you sure?' } %>
                	</li>
                </ul>
            </div>
        </div>
    </div>
</div>